export type MCQQuestion = {
  id: string;
  level: "Level 1";
  subtopic: "Health and Safety";
  sourceLessonId?: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  tags: string[];
};

export const level1HealthSafetyQuestions: MCQQuestion[] = [
  {
    id: "L1-HS-001",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What does a PAT testing label on a tool tell you?",
    options: [
      "The next test due date",
      "The tool model number",
      "The tool purchase price",
      "The manufacturer warranty length",
    ],
    correctIndex: 0,
    explanation: "PAT labels show the test date and when the next test is due.",
    tags: ["electricity", "pat"],
  },
  {
    id: "L1-HS-002",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Why is PAT testing carried out on portable tools?",
    options: [
      "To check they are electrically safe to use",
      "To improve the tool speed",
      "To change the voltage rating",
      "To sharpen the cutting blades",
    ],
    correctIndex: 0,
    explanation: "PAT testing confirms electrical safety before use.",
    tags: ["electricity", "pat"],
  },
  {
    id: "L1-HS-003",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What is the standard site voltage for portable tools?",
    options: ["110V", "230V", "415V", "12V"],
    correctIndex: 0,
    explanation: "Sites commonly use reduced low voltage 110V for safety.",
    tags: ["electricity"],
  },
  {
    id: "L1-HS-004",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "How are 110V site tools typically identified?",
    options: [
      "Yellow plugs and cables",
      "Blue plugs and cables",
      "Red plugs and cables",
      "Black plugs and cables",
    ],
    correctIndex: 0,
    explanation: "Yellow plugs and leads indicate 110V site equipment.",
    tags: ["electricity"],
  },
  {
    id: "L1-HS-005",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Why is 110V used on site instead of 230V?",
    options: [
      "It reduces the risk of electric shock",
      "It makes tools run faster",
      "It is cheaper to power",
      "It eliminates the need for fuses",
    ],
    correctIndex: 0,
    explanation: "Reduced low voltage lowers the severity of electric shock.",
    tags: ["electricity"],
  },
  {
    id: "L1-HS-006",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Where should a petrol generator be positioned on site?",
    options: [
      "Outside in a well-ventilated area",
      "Inside a store with doors closed",
      "Under a staircase",
      "In a corridor near exits",
    ],
    correctIndex: 0,
    explanation: "Generators must be outside to prevent fume build-up.",
    tags: ["generator", "fumes"],
  },
  {
    id: "L1-HS-007",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Why must generator exhaust fumes be kept away from openings?",
    options: [
      "Fumes can be deadly if they build up indoors",
      "They rust metal tools",
      "They make tools run slower",
      "They reduce battery life",
    ],
    correctIndex: 0,
    explanation: "Exhaust fumes contain carbon monoxide and must not enter buildings.",
    tags: ["generator", "fumes"],
  },
  {
    id: "L1-HS-008",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What is the correct color for the live wire in a plug?",
    options: ["Brown", "Blue", "Green/yellow", "Black"],
    correctIndex: 0,
    explanation: "Brown is the live conductor in modern wiring.",
    tags: ["electricity", "plug"],
  },
  {
    id: "L1-HS-009",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What is the correct color for the neutral wire?",
    options: ["Blue", "Brown", "Green/yellow", "Red"],
    correctIndex: 0,
    explanation: "Blue identifies the neutral conductor.",
    tags: ["electricity", "plug"],
  },
  {
    id: "L1-HS-010",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What is the correct color for the earth wire?",
    options: ["Green/yellow", "Blue", "Brown", "Grey"],
    correctIndex: 0,
    explanation: "Green/yellow indicates the earth conductor.",
    tags: ["electricity", "plug"],
  },
  {
    id: "L1-HS-011",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What is the purpose of the earth wire?",
    options: [
      "To provide a safe path to ground in a fault",
      "To carry the main power",
      "To control tool speed",
      "To reduce tool weight",
    ],
    correctIndex: 0,
    explanation: "The earth wire provides a safe fault path and trips protection.",
    tags: ["electricity", "earth"],
  },
  {
    id: "L1-HS-012",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which symbol shows a tool is double insulated?",
    options: [
      "A square inside a square",
      "A lightning bolt",
      "A triangle with an exclamation mark",
      "A circle with a line through it",
    ],
    correctIndex: 0,
    explanation: "Double-insulated tools carry the square-in-square symbol.",
    tags: ["electricity", "tools"],
  },
  {
    id: "L1-HS-013",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Why do double-insulated tools not need an earth wire?",
    options: [
      "They have extra insulation to protect users",
      "They only run on batteries",
      "They are powered by air",
      "They are used outdoors only",
    ],
    correctIndex: 0,
    explanation: "Double insulation protects users without an earth connection.",
    tags: ["electricity", "tools"],
  },
  {
    id: "L1-HS-014",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Who is allowed to repair damaged electrical equipment on site?",
    options: [
      "A competent, qualified person",
      "Any apprentice",
      "Anyone with spare tape",
      "The site cleaner",
    ],
    correctIndex: 0,
    explanation: "Electrical repairs must be done by a competent person.",
    tags: ["electricity"],
  },
  {
    id: "L1-HS-015",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What should you do with a damaged power lead?",
    options: [
      "Remove it from service and report it",
      "Wrap it with tape and keep using",
      "Ignore it if it still works",
      "Cut off the plug and rewire it yourself",
    ],
    correctIndex: 0,
    explanation: "Damaged leads must be taken out of use and reported.",
    tags: ["electricity"],
  },
  {
    id: "L1-HS-016",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "How should battery packs be charged on site?",
    options: [
      "Using the correct charger in a safe area",
      "Next to flammable materials",
      "On a wet surface",
      "In direct sunlight",
    ],
    correctIndex: 0,
    explanation: "Use the correct charger and a safe, dry location.",
    tags: ["battery"],
  },
  {
    id: "L1-HS-017",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What should you do with a swollen or damaged battery?",
    options: [
      "Remove it from use and report it",
      "Continue using it until empty",
      "Charge it overnight",
      "Puncture it to release pressure",
    ],
    correctIndex: 0,
    explanation: "Damaged batteries are unsafe and must be removed from use.",
    tags: ["battery"],
  },
  {
    id: "L1-HS-018",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "How should batteries be stored when not in use?",
    options: [
      "In a cool, dry place away from metal objects",
      "On the floor near walkways",
      "In direct sunlight",
      "Beside fuel cans",
    ],
    correctIndex: 0,
    explanation: "Cool, dry storage reduces risk of damage and shorting.",
    tags: ["battery"],
  },
  {
    id: "L1-HS-019",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Why is good storage important on site?",
    options: [
      "It reduces trip hazards and damage",
      "It makes tools look newer",
      "It increases working hours",
      "It keeps paint wetter",
    ],
    correctIndex: 0,
    explanation: "Good storage prevents trips and protects materials.",
    tags: ["housekeeping"],
  },
  {
    id: "L1-HS-020",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What is a common cause of trips on site?",
    options: [
      "Poor housekeeping and trailing leads",
      "Too many signs",
      "Short break times",
      "Hard hats",
    ],
    correctIndex: 0,
    explanation: "Untidy areas and leads across walkways cause trips.",
    tags: ["housekeeping", "trips"],
  },
  {
    id: "L1-HS-021",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Where does PPE sit in the hierarchy of control?",
    options: [
      "Last resort after other controls",
      "First and only control",
      "Above elimination",
      "Above substitution",
    ],
    correctIndex: 0,
    explanation: "PPE is the final control after other measures.",
    tags: ["ppe"],
  },
  {
    id: "L1-HS-022",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which option is highest in the hierarchy of control?",
    options: ["Elimination", "PPE", "Warning signs", "Training"],
    correctIndex: 0,
    explanation: "Elimination removes the hazard entirely.",
    tags: ["ppe", "controls"],
  },
  {
    id: "L1-HS-023",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Who must provide suitable PPE on site?",
    options: [
      "The employer",
      "The tool supplier",
      "The client",
      "The local council",
    ],
    correctIndex: 0,
    explanation: "Employers must provide suitable PPE.",
    tags: ["ppe"],
  },
  {
    id: "L1-HS-024",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What is the worker's duty regarding PPE?",
    options: [
      "Wear it correctly and keep it in good condition",
      "Only wear it when convenient",
      "Modify it for comfort",
      "Lend it to visitors",
    ],
    correctIndex: 0,
    explanation: "Workers must wear PPE properly and look after it.",
    tags: ["ppe"],
  },
  {
    id: "L1-HS-025",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "When is a face-fit test required for RPE?",
    options: [
      "For tight-fitting masks",
      "For loose-fitting hoods only",
      "For hearing protection",
      "For gloves",
    ],
    correctIndex: 0,
    explanation: "Tight-fitting RPE needs a face-fit test to ensure a seal.",
    tags: ["rpe", "ppe"],
  },
  {
    id: "L1-HS-026",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What are the three elements of the fire triangle?",
    options: [
      "Heat, fuel, oxygen",
      "Water, fuel, oxygen",
      "Heat, smoke, sparks",
      "Fuel, foam, gas",
    ],
    correctIndex: 0,
    explanation: "Fire needs heat, fuel, and oxygen to burn.",
    tags: ["fire"],
  },
  {
    id: "L1-HS-027",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "How do you stop a fire from spreading?",
    options: [
      "Remove one element of the fire triangle",
      "Add more oxygen",
      "Open windows to feed it",
      "Move fuel closer",
    ],
    correctIndex: 0,
    explanation: "Removing heat, fuel, or oxygen stops the fire.",
    tags: ["fire"],
  },
  {
    id: "L1-HS-028",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Why is good housekeeping important for fire safety?",
    options: [
      "It reduces fuel sources and trip hazards",
      "It makes paint dry faster",
      "It stops tools from rusting",
      "It increases noise levels",
    ],
    correctIndex: 0,
    explanation: "Keeping areas clear reduces both fire load and trips.",
    tags: ["housekeeping", "fire"],
  },
  {
    id: "L1-HS-029",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What should you do when a fire alarm sounds?",
    options: [
      "Stop work and go to the assembly point",
      "Finish the task first",
      "Hide in the nearest room",
      "Silence the alarm",
    ],
    correctIndex: 0,
    explanation: "Evacuate immediately and go to the assembly point.",
    tags: ["fire", "evacuation"],
  },
  {
    id: "L1-HS-030",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which extinguisher is suitable for wood and paper fires?",
    options: ["Water", "CO2", "Wet chemical", "Gas"],
    correctIndex: 0,
    explanation: "Water extinguishers are for Class A fires like wood and paper.",
    tags: ["fire", "extinguisher"],
  },
  {
    id: "L1-HS-031",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which extinguisher is suitable for electrical fires?",
    options: ["CO2", "Water", "Foam", "Wet chemical"],
    correctIndex: 0,
    explanation: "CO2 is safe for live electrical equipment.",
    tags: ["fire", "extinguisher"],
  },
  {
    id: "L1-HS-032",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which extinguisher is commonly used for flammable liquids?",
    options: ["Foam", "Water", "CO2 only", "Sand"],
    correctIndex: 0,
    explanation: "Foam extinguishers are suitable for flammable liquids.",
    tags: ["fire", "extinguisher"],
  },
  {
    id: "L1-HS-033",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which extinguisher is considered multipurpose but leaves residue?",
    options: ["Dry powder", "CO2", "Water", "Foam"],
    correctIndex: 0,
    explanation: "Dry powder is multipurpose but can leave a messy residue.",
    tags: ["fire", "extinguisher"],
  },
  {
    id: "L1-HS-034",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which topic is normally covered in a site induction?",
    options: [
      "Emergency procedures and site rules",
      "Personal banking details",
      "Material price lists",
      "Tool brand preferences",
    ],
    correctIndex: 0,
    explanation: "Induction covers safety rules, hazards, and emergency actions.",
    tags: ["induction"],
  },
  {
    id: "L1-HS-035",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What does COSHH stand for?",
    options: [
      "Control of Substances Hazardous to Health",
      "Construction of Safe Site Homes",
      "Code of Safety for Heavy Handling",
      "Control of Site Safety Hazards",
    ],
    correctIndex: 0,
    explanation: "COSHH covers hazardous substances and safe handling.",
    tags: ["coshh"],
  },
  {
    id: "L1-HS-036",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Where do you find safe handling and hazard details for a product?",
    options: [
      "Safety Data Sheet (SDS)",
      "Delivery note",
      "Timesheet",
      "Tool manual",
    ],
    correctIndex: 0,
    explanation: "The SDS provides hazards, PPE, and first aid guidance.",
    tags: ["coshh", "sds"],
  },
  {
    id: "L1-HS-037",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Under HASAWA, what is an employer required to provide?",
    options: [
      "Safe systems of work and training",
      "Free meals",
      "Personal tools",
      "Company cars",
    ],
    correctIndex: 0,
    explanation: "Employers must provide safe systems and information/training.",
    tags: ["hasawa"],
  },
  {
    id: "L1-HS-038",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Under HASAWA, what must employees do?",
    options: [
      "Take reasonable care and cooperate with safety rules",
      "Write risk assessments",
      "Inspect scaffolds weekly",
      "Set site speed limits",
    ],
    correctIndex: 0,
    explanation: "Employees must take care and follow safety procedures.",
    tags: ["hasawa"],
  },
  {
    id: "L1-HS-039",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What does an HSE prohibition notice mean?",
    options: [
      "Work must stop immediately",
      "Work can continue for 7 days",
      "Only paperwork needs updating",
      "It is a warning with no action",
    ],
    correctIndex: 0,
    explanation: "A prohibition notice stops the activity straight away.",
    tags: ["hse"],
  },
  {
    id: "L1-HS-040",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What does an HSE improvement notice require?",
    options: [
      "Fix the issue by a stated deadline",
      "Stop work immediately",
      "Pay a fine on the spot",
      "Ignore the issue",
    ],
    correctIndex: 0,
    explanation: "Improvement notices give time to correct the problem.",
    tags: ["hse"],
  },
  {
    id: "L1-HS-041",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which welfare facility must be provided on site?",
    options: ["Toilets and washing facilities", "Showers only", "Gym", "Wi-Fi"],
    correctIndex: 0,
    explanation: "Basic welfare includes toilets and washing facilities.",
    tags: ["welfare"],
  },
  {
    id: "L1-HS-042",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which safety sign indicates a mandatory action?",
    options: [
      "Blue circle",
      "Yellow triangle",
      "Red circle with slash",
      "Green rectangle",
    ],
    correctIndex: 0,
    explanation: "Mandatory signs are blue circles.",
    tags: ["signs"],
  },
  {
    id: "L1-HS-043",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which safety sign is used for warnings?",
    options: [
      "Yellow triangle",
      "Blue circle",
      "Green rectangle",
      "Red square",
    ],
    correctIndex: 0,
    explanation: "Warning signs are yellow triangles.",
    tags: ["signs"],
  },
  {
    id: "L1-HS-044",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which safety sign indicates prohibition?",
    options: [
      "Red circle with a diagonal line",
      "Green rectangle",
      "Yellow triangle",
      "Blue circle",
    ],
    correctIndex: 0,
    explanation: "Prohibition signs are red circles with a slash.",
    tags: ["signs"],
  },
  {
    id: "L1-HS-045",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which safety sign indicates a safe condition?",
    options: [
      "Green rectangle",
      "Red circle",
      "Yellow triangle",
      "Blue triangle",
    ],
    correctIndex: 0,
    explanation: "Safe condition signs are green rectangles or squares.",
    tags: ["signs"],
  },
  {
    id: "L1-HS-046",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Where does the live wire connect in a plug?",
    options: ["L terminal", "N terminal", "E terminal", "Case screw"],
    correctIndex: 0,
    explanation: "The live conductor goes to the L terminal.",
    tags: ["plug", "electricity"],
  },
  {
    id: "L1-HS-047",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Where does the neutral wire connect in a plug?",
    options: ["N terminal", "L terminal", "E terminal", "Fuse holder"],
    correctIndex: 0,
    explanation: "The neutral conductor goes to the N terminal.",
    tags: ["plug", "electricity"],
  },
  {
    id: "L1-HS-048",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Where does the earth wire connect in a plug?",
    options: ["E terminal", "L terminal", "N terminal", "Fuse clip"],
    correctIndex: 0,
    explanation: "The earth conductor connects to the E terminal.",
    tags: ["plug", "electricity"],
  },
  {
    id: "L1-HS-049",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What is the purpose of the fuse in a plug?",
    options: [
      "To protect the cable from overload",
      "To make the tool start faster",
      "To provide earth protection",
      "To reduce noise",
    ],
    correctIndex: 0,
    explanation: "The fuse protects the cable by breaking the circuit on overload.",
    tags: ["plug", "electricity"],
  },
  {
    id: "L1-HS-050",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What should you check before using a power tool?",
    options: [
      "Cable, plug, and casing for damage",
      "Only the color of the tool",
      "Only the battery brand",
      "Only the speed dial",
    ],
    correctIndex: 0,
    explanation: "A visual inspection checks for damage before use.",
    tags: ["electricity", "tools"],
  },
  {
    id: "L1-HS-051",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "How should trailing leads be managed on site?",
    options: [
      "Routed away from walkways or covered",
      "Left across doorways",
      "Coiled tightly while in use",
      "Hidden under loose materials",
    ],
    correctIndex: 0,
    explanation: "Leads must be routed safely to prevent trips.",
    tags: ["housekeeping", "trips"],
  },
  {
    id: "L1-HS-052",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What should you do before refueling a generator?",
    options: [
      "Switch it off and allow it to cool",
      "Refuel while it is running",
      "Move it inside",
      "Pour fuel on the exhaust",
    ],
    correctIndex: 0,
    explanation: "Refuel only when off and cool to avoid fire.",
    tags: ["generator", "fire"],
  },
  {
    id: "L1-HS-053",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which statement about 110V tools is correct?",
    options: [
      "They reduce risk but do not remove it",
      "They are always safe to use in water",
      "They never need testing",
      "They cannot give a shock",
    ],
    correctIndex: 0,
    explanation: "110V lowers risk but still requires safe use.",
    tags: ["electricity"],
  },
  {
    id: "L1-HS-054",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which is a correct reason to wear eye protection?",
    options: [
      "To protect against flying debris",
      "To reduce noise",
      "To improve grip",
      "To keep hands clean",
    ],
    correctIndex: 0,
    explanation: "Eye protection guards against chips and dust.",
    tags: ["ppe"],
  },
  {
    id: "L1-HS-055",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "When should hearing protection be used?",
    options: [
      "When noise levels are high",
      "Only during breaks",
      "Only outdoors",
      "Only after lunch",
    ],
    correctIndex: 0,
    explanation: "Hearing protection is required when noise is excessive.",
    tags: ["ppe"],
  },
  {
    id: "L1-HS-056",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "How can dust exposure be reduced during cutting?",
    options: [
      "Use extraction and suitable RPE",
      "Remove guards",
      "Cut faster without extraction",
      "Sweep dust into the air",
    ],
    correctIndex: 0,
    explanation: "Extraction and RPE reduce inhalation risk.",
    tags: ["rpe", "dust"],
  },
  {
    id: "L1-HS-057",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which item should be included in a site induction?",
    options: [
      "First aid arrangements",
      "Personal wage rates",
      "Holiday requests",
      "Customer complaints",
    ],
    correctIndex: 0,
    explanation: "Induction covers emergency procedures and first aid info.",
    tags: ["induction"],
  },
  {
    id: "L1-HS-058",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What does an SDS tell you about a product?",
    options: [
      "Hazards, safe use, and first aid",
      "Supplier profit margins",
      "Delivery schedules",
      "Tool service intervals",
    ],
    correctIndex: 0,
    explanation: "SDS provides safety information and emergency guidance.",
    tags: ["sds", "coshh"],
  },
  {
    id: "L1-HS-059",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "Which welfare facility must be available for workers?",
    options: [
      "Drinking water",
      "Private office",
      "Company car",
      "Laundry service",
    ],
    correctIndex: 0,
    explanation: "Potable drinking water is a basic welfare requirement.",
    tags: ["welfare"],
  },
  {
    id: "L1-HS-060",
    level: "Level 1",
    subtopic: "Health and Safety",
    question: "What should you do if you are unsure about a safety procedure?",
    options: [
      "Ask a supervisor or safety representative",
      "Guess and carry on",
      "Wait until the end of the day",
      "Ignore it if others seem fine",
    ],
    correctIndex: 0,
    explanation: "Always ask for clarification before proceeding.",
    tags: ["induction", "general"],
  },
];
